{{- if .Values.auth.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "llm-helm-deployer.fullname" . }}-apikey
  labels:
    {{- include "llm-helm-deployer.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.auth.apiKey | b64enc | quote }}
{{- end }}
