{{- if .Values.metrics.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "llm-helm-deployer.fullname" . }}
  labels:
    {{- include "llm-helm-deployer.labels" . | nindent 4 }}
    {{- $userLabels := .Values.metrics.serviceMonitor.labels | default dict }}
    {{- if and (index .Values "kube-prometheus-stack" "enabled") (not (hasKey $userLabels "release")) }}
    release: {{ .Release.Name }}
    {{- end }}
    {{- with $userLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "llm-helm-deployer.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
